import { useEffect, useRef } from "react";
import { useApp } from "../state/store";
import { extColor, extOf, fmtSize } from "../lib/format";

export default function FilesPanel() {
  const { files, loadFiles, downloadFile, library, libraryHealth, loadLibrary, uploadFiles, deleteLibrary } = useApp();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    loadFiles();
    loadLibrary();
  }, [loadFiles, loadLibrary]);

  const usedPct = libraryHealth
    ? Math.min(100, Math.round((libraryHealth.used_bytes / (libraryHealth.used_bytes + libraryHealth.free_bytes)) * 100))
    : 0;

  return (
    <div style={{ padding: "14px 16px 20px" }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: "var(--lo)", textTransform: "uppercase", letterSpacing: ".07em", marginBottom: 9 }}>
        Generated by this session
      </div>
      {files.length === 0 && <div style={{ fontSize: 12, color: "var(--lo)", marginBottom: 8 }}>No files yet.</div>}
      {files.map((f) => {
        const ext = extOf(f.path);
        return (
          <div key={f.path} style={{ display: "flex", alignItems: "center", gap: 11, padding: "10px 11px", border: "1px solid var(--border)", borderRadius: 9, marginBottom: 7, background: "var(--bg2)" }}>
            <span style={{ fontFamily: "var(--mono)", fontSize: 10, fontWeight: 600, padding: "3px 6px", borderRadius: 5, background: "var(--bg3)", color: extColor(ext) }}>{ext}</span>
            <span style={{ flex: 1, minWidth: 0 }}>
              <span style={{ display: "block", fontFamily: "var(--mono)", fontSize: 12, color: "var(--hi)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{f.path}</span>
              <span style={{ fontSize: 10.5, color: "var(--lo)" }}>{fmtSize(f.size)}</span>
            </span>
            <button onClick={() => downloadFile(f.path)} style={{ fontSize: 11, color: "var(--accent)", fontFamily: "var(--mono)", padding: "4px 9px", borderRadius: 6, border: "1px solid var(--border)" }}>
              get
            </button>
          </div>
        );
      })}

      <div style={{ fontSize: 11, fontWeight: 600, color: "var(--lo)", textTransform: "uppercase", letterSpacing: ".07em", margin: "18px 0 9px" }}>
        Shared library
      </div>
      <label style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 7, padding: 12, border: "1px dashed var(--border-hi)", borderRadius: 9, color: "var(--mid)", fontSize: 12.5, cursor: "pointer", marginBottom: 9 }}>
        <span style={{ fontSize: 15 }}>{"\u2191"}</span> Drop files or click to upload
        <input
          ref={inputRef}
          type="file"
          multiple
          onChange={(e) => {
            if (e.target.files) void uploadFiles(e.target.files);
            if (inputRef.current) inputRef.current.value = "";
          }}
          style={{ display: "none" }}
        />
      </label>
      {library.map((f) => {
        const ext = extOf(f.name);
        return (
          <div key={f.name} style={{ display: "flex", alignItems: "center", gap: 11, padding: "9px 11px", borderBottom: "1px solid var(--border)" }}>
            <span style={{ fontFamily: "var(--mono)", fontSize: 10, fontWeight: 600, padding: "3px 6px", borderRadius: 5, background: "var(--bg2)", color: extColor(ext) }}>{ext}</span>
            <span style={{ flex: 1, minWidth: 0 }}>
              <span style={{ display: "block", fontFamily: "var(--mono)", fontSize: 12, color: "var(--hi)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{f.name}</span>
              <span style={{ fontSize: 10.5, color: "var(--lo)" }}>{fmtSize(f.size)}</span>
            </span>
            <button onClick={() => void deleteLibrary(f.name)} style={{ fontSize: 12, color: "var(--lo)", padding: "3px 7px" }}>
              {"\u2715"}
            </button>
          </div>
        );
      })}
      {libraryHealth && (
        <div style={{ marginTop: 12, display: "flex", alignItems: "center", gap: 8, fontSize: 11, color: "var(--lo)" }}>
          <span style={{ flex: 1, height: 4, borderRadius: 3, background: "var(--bg3)", overflow: "hidden" }}>
            <span style={{ display: "block", width: `${usedPct}%`, height: "100%", background: "var(--accent)" }} />
          </span>
          <span style={{ fontFamily: "var(--mono)" }}>
            {fmtSize(libraryHealth.used_bytes)} used · {fmtSize(libraryHealth.free_bytes)} free
          </span>
        </div>
      )}
    </div>
  );
}
