import { useMemo, useState } from "react";
import type { HypSession } from "../lib/types";

// The parallel-set hypothesis explorer, factored out of HypothesisView so the
// onboarding wizard (O1) and the Hypotheses page render the same cards and
// drive the same refine/select actions. Pure presentation + callbacks: the
// caller owns the session record and the API calls.

export interface HypothesisCardsProps {
  session: HypSession;
  loading: string | null;
  onSelect: (hypId: string) => void;
  onRefine: (parentId: string, feedback: string) => void;
}

export default function HypothesisCards({ session, loading, onSelect, onRefine }: HypothesisCardsProps) {
  const [viewRound, setViewRound] = useState(session.rounds.length - 1);
  const [refiningId, setRefiningId] = useState<string | null>(null);
  const [feedback, setFeedback] = useState("");

  // A new round appended by the caller (after a refine) should be shown.
  const lastRound = session.rounds.length - 1;
  const roundIdx = Math.min(viewRound, lastRound);
  const [seenRounds, setSeenRounds] = useState(session.rounds.length);
  if (session.rounds.length !== seenRounds) {
    setSeenRounds(session.rounds.length);
    setViewRound(lastRound);
    setRefiningId(null);
    setFeedback("");
  }

  const round = session.rounds[roundIdx] ?? null;
  const parentCard = useMemo(() => {
    if (!round || round.parent_id == null) return null;
    for (const r of session.rounds) {
      const p = r.hypotheses.find((h) => h.id === round.parent_id);
      if (p) return p;
    }
    return null;
  }, [session, round]);

  return (
    <div>
      {/* round nav */}
      {session.rounds.length > 1 && (
        <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 12, flexWrap: "wrap" }}>
          {session.rounds.map((_r, i) => (
            <button
              key={i}
              onClick={() => { setViewRound(i); setRefiningId(null); }}
              style={{ fontFamily: "var(--mono)", fontSize: 11, padding: "4px 10px", borderRadius: 7, border: `1px solid ${i === roundIdx ? "var(--accent)" : "var(--border)"}`, background: i === roundIdx ? "var(--accent-soft)" : "transparent", color: i === roundIdx ? "var(--accent)" : "var(--mid)" }}
            >
              {i === 0 ? "Round 1 · goal" : `Round ${i + 1}`}
            </button>
          ))}
        </div>
      )}

      {/* lineage for refined rounds */}
      {parentCard && (
        <div style={{ marginBottom: 14, padding: "10px 13px", background: "var(--bg2)", border: "1px solid var(--border)", borderLeft: "2px solid var(--accent)", borderRadius: "0 9px 9px 0" }}>
          <div style={{ fontSize: 10.5, fontWeight: 600, color: "var(--lo)", textTransform: "uppercase", letterSpacing: ".06em" }}>Refined from</div>
          <div style={{ marginTop: 3, fontSize: 12.5, color: "var(--hi)", lineHeight: 1.4 }}>{parentCard.statement}</div>
          {round?.feedback && (
            <div style={{ marginTop: 5, fontSize: 12, color: "var(--mid)" }}>
              <span style={{ color: "var(--lo)" }}>your steer: </span>{round.feedback}
            </div>
          )}
        </div>
      )}

      {round && (
        <div style={{ marginBottom: 10, fontSize: 11, color: "var(--lo)", fontFamily: "var(--mono)" }}>
          {round.hypotheses.length} parallel hypotheses · generated by {round.served_by}
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 12, opacity: loading ? 0.5 : 1, transition: "opacity .2s", pointerEvents: loading ? "none" : "auto" }}>
        {round?.hypotheses.map((h, i) => {
          const selected = session.selected_id === h.id;
          const open = refiningId === h.id;
          return (
            <div key={h.id} style={{ border: `1.5px solid ${selected ? "var(--ok)" : "var(--border)"}`, background: selected ? "var(--ok-soft)" : "var(--bg1)", borderRadius: 12, padding: "14px 15px", display: "flex", flexDirection: "column", gap: 8 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <span style={{ fontFamily: "var(--mono)", fontSize: 10, fontWeight: 700, color: "var(--accent)" }}>{String.fromCharCode(65 + i)}</span>
                {selected && <span style={{ fontFamily: "var(--mono)", fontSize: 9.5, fontWeight: 700, padding: "1px 6px", borderRadius: 5, background: "var(--ok)", color: "#04160c", textTransform: "uppercase", letterSpacing: ".05em" }}>working hypothesis</span>}
              </div>
              <div style={{ fontSize: 14, fontWeight: 600, color: "var(--hi)", lineHeight: 1.35 }}>{h.statement}</div>
              {h.rationale && <div style={{ fontSize: 12.5, color: "var(--mid)", lineHeight: 1.5 }}>{h.rationale}</div>}
              <div style={{ flex: 1 }} />
              <div style={{ display: "flex", gap: 8, marginTop: 2 }}>
                <button onClick={() => onSelect(h.id)} style={{ flex: 1, padding: "8px 10px", background: selected ? "var(--bg2)" : "var(--ok)", color: selected ? "var(--mid)" : "#04160c", border: selected ? "1px solid var(--border)" : "none", fontWeight: 700, borderRadius: 8, fontSize: 12.5 }}>
                  {selected ? "Selected ✓" : "Select"}
                </button>
                <button onClick={() => { setRefiningId(open ? null : h.id); setFeedback(""); }} style={{ flex: 1, padding: "8px 10px", background: open ? "var(--accent-soft)" : "var(--bg2)", color: "var(--accent)", border: `1px solid ${open ? "var(--accent)" : "var(--border)"}`, fontWeight: 600, borderRadius: 8, fontSize: 12.5 }}>
                  Explore from this →
                </button>
              </div>
              {open && (
                <div style={{ marginTop: 4, display: "flex", flexDirection: "column", gap: 7 }}>
                  <textarea
                    autoFocus
                    value={feedback}
                    onChange={(e) => setFeedback(e.target.value)}
                    placeholder="What should the next set do differently? (optional)"
                    rows={2}
                    style={{ resize: "none", padding: "8px 10px", background: "var(--bg0)", border: "1px solid var(--border)", borderRadius: 8, color: "var(--hi)", fontSize: 12.5, outline: "none" }}
                  />
                  <button onClick={() => onRefine(h.id, feedback.trim())} style={{ padding: "8px 10px", background: "var(--accent)", color: "#06121c", fontWeight: 700, borderRadius: 8, fontSize: 12.5 }}>
                    Generate a new set from this
                  </button>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {loading && (
        <div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 10, color: "var(--mid)", fontSize: 13 }}>
          <span style={{ width: 9, height: 9, borderRadius: "50%", background: "var(--accent)", animation: "pulse 1.4s infinite" }} />
          {loading} <span style={{ color: "var(--lo)", fontSize: 12 }}>(can take up to a minute)</span>
        </div>
      )}
    </div>
  );
}
